#!/usr/bin/env python3
"""
build_index.py
Scans the /posts directory for all .md files, reads their YAML frontmatter,
and writes a sorted posts/index.json manifest.

Run manually:  python3 scripts/build_index.py
Auto-run by:   .github/workflows/rebuild-posts-index.yml on every push
"""

import os
import re
import json
from pathlib import Path

POSTS_DIR   = Path(__file__).parent.parent / "posts"
OUTPUT_FILE = POSTS_DIR / "index.json"

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
# Handles:  key: value  OR  key: "value"  OR  key: 'value'
FIELD_RE = re.compile(r'^(\w+)\s*:\s*(.+)$')


def parse_frontmatter(text: str) -> dict:
    """Extract YAML frontmatter fields from a Markdown file."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}

    data = {}
    block = match.group(1)

    for line in block.splitlines():
        m = FIELD_RE.match(line.strip())
        if not m:
            continue
        key   = m.group(1).strip()
        value = m.group(2).strip().strip('"\'')

        # Handle inline arrays: [item1, item2, "item3"]
        if value.startswith('[') and value.endswith(']'):
            inner = value[1:-1]
            value = [v.strip().strip('"\'') for v in inner.split(',') if v.strip()]

        # Handle booleans
        if isinstance(value, str):
            if value.lower() == 'true':
                value = True
            elif value.lower() == 'false':
                value = False

        data[key] = value

    return data


def build():
    posts = []

    for md_file in sorted(POSTS_DIR.glob("*.md")):
        slug = md_file.stem
        try:
            content = md_file.read_text(encoding="utf-8")
        except Exception as e:
            print(f"  ⚠ Could not read {md_file.name}: {e}")
            continue

        meta = parse_frontmatter(content)

        if not meta.get("title"):
            print(f"  ⚠ Skipping {md_file.name} — missing 'title' in frontmatter")
            continue

        post_entry = {
            "slug":       slug,
            "title":      meta.get("title", slug),
            "date":       meta.get("date", ""),
            "emoji":      meta.get("emoji", "📝"),
            "category":   meta.get("category", ""),
            "tags":       meta.get("tags", []),
            "excerpt":    meta.get("excerpt", ""),
            "author":     meta.get("author", ""),
            "featured":   meta.get("featured", False),
            "coverImage": meta.get("coverImage", ""),
        }

        # Ensure tags is always a list
        if isinstance(post_entry["tags"], str):
            post_entry["tags"] = [t.strip() for t in post_entry["tags"].split(",")]

        posts.append(post_entry)
        print(f"  ✅ {slug}")

    # Sort by date descending (newest first), then title
    posts.sort(key=lambda p: (p.get("date") or ""), reverse=True)

    output = {
        "_note": "Auto-generated by scripts/build_index.py — do not edit manually.",
        "posts": posts,
    }

    OUTPUT_FILE.write_text(
        json.dumps(output, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"\n✨ Written {len(posts)} post(s) to {OUTPUT_FILE.relative_to(Path.cwd())}")


if __name__ == "__main__":
    print(f"📂 Scanning {POSTS_DIR.relative_to(Path.cwd())} for Markdown posts...\n")
    build()
